/**
 * @typedef {import('pokedex-promise-v2').Ability} Ability
 * @typedef {import('pokedex-promise-v2').Berry} Berry
 * @typedef {import('pokedex-promise-v2').BerryFirmness} BerryFirmness
 * @typedef {import('pokedex-promise-v2').BerryFlavor} BerryFlavor
 * @typedef {import('pokedex-promise-v2').Characteristic} Characteristic
 * @typedef {import('pokedex-promise-v2').ContestEffect} ContestEffect
 * @typedef {import('pokedex-promise-v2').ContestType} ContestType
 * @typedef {import('pokedex-promise-v2').EggGroup} EggGroup
 * @typedef {import('pokedex-promise-v2').EncounterCondition} EncounterCondition
 * @typedef {import('pokedex-promise-v2').EncounterConditionValue} EncounterConditionValue
 * @typedef {import('pokedex-promise-v2').EncounterMethod} EncounterMethod
 * @typedef {import('pokedex-promise-v2').EvolutionChain} EvolutionChain
 * @typedef {import('pokedex-promise-v2').EvolutionTrigger} EvolutionTrigger
 * @typedef {import('pokedex-promise-v2').Gender} Gender
 * @typedef {import('pokedex-promise-v2').Generation} Generation
 * @typedef {import('pokedex-promise-v2').GrowthRate} GrowthRate
 * @typedef {import('pokedex-promise-v2').Item} Item
 * @typedef {import('pokedex-promise-v2').ItemAttribute} ItemAttribute
 * @typedef {import('pokedex-promise-v2').ItemCategory} ItemCategory
 * @typedef {import('pokedex-promise-v2').ItemFlingEffect} ItemFlingEffect
 * @typedef {import('pokedex-promise-v2').ItemPocket} ItemPocket
 * @typedef {import('pokedex-promise-v2').Language} Language
 * @typedef {import('pokedex-promise-v2').Location} PokedexLocation
 * @typedef {import('pokedex-promise-v2').LocationArea} LocationArea
 * @typedef {import('pokedex-promise-v2').Machine} Machine
 * @typedef {import('pokedex-promise-v2').Move} Move
 * @typedef {import('pokedex-promise-v2').MoveAilment} MoveAilment
 * @typedef {import('pokedex-promise-v2').MoveBattleStyle} MoveBattleStyle
 * @typedef {import('pokedex-promise-v2').MoveCategory} MoveCategory
 * @typedef {import('pokedex-promise-v2').MoveDamageClass} MoveDamageClass
 * @typedef {import('pokedex-promise-v2').MoveLearnMethod} MoveLearnMethod
 * @typedef {import('pokedex-promise-v2').MoveTarget} MoveTarget
 * @typedef {import('pokedex-promise-v2').Nature} Nature
 * @typedef {import('pokedex-promise-v2').PalParkArea} PalParkArea
 * @typedef {import('pokedex-promise-v2').PokeathlonStat} PokeathlonStat
 * @typedef {import('pokedex-promise-v2').Pokedex} Pokedex
 * @typedef {import('pokedex-promise-v2').Pokemon} Pokemon
 * @typedef {import('pokedex-promise-v2').PokemonColor} PokemonColor
 * @typedef {import('pokedex-promise-v2').PokemonForm} PokemonForm
 * @typedef {import('pokedex-promise-v2').PokemonHabitat} PokemonHabitat
 * @typedef {import('pokedex-promise-v2').PokemonShape} PokemonShape
 * @typedef {import('pokedex-promise-v2').PokemonSpecies} PokemonSpecies
 * @typedef {import('pokedex-promise-v2').Region} Region
 * @typedef {import('pokedex-promise-v2').Stat} Stat
 * @typedef {import('pokedex-promise-v2').SuperContestEffect} SuperContestEffect
 * @typedef {import('pokedex-promise-v2').Type} Type
 * @typedef {import('pokedex-promise-v2').Version} Version
 * @typedef {import('pokedex-promise-v2').VersionGroup} VersionGroup
 */
